[theme]
base="dark"
primaryColor="#fc235a"
backgroundColor="#040138"
secondaryBackgroundColor="#221e5b"

#[theme] - 1
#base="dark"
#primaryColor="#47b57d"
#backgroundColor="#0f172b"
#secondaryBackgroundColor="#1e293b"


#[theme] - 2
#base="dark"
#primaryColor="#1de9aa"
#backgroundColor="#1d0f4a"
#secondaryBackgroundColor="#281b54"